application:
version: 1
runtime: go
api_version: go1

handlers:
- url: /cron/.*
  script: _go_app
  login: admin
- url: /task/.*
  script: _go_app
  login: admin
- url: /api/1/.*
  script: _go_app
  secure: always
# - url: /.*
#   script: _go_app
#   secure: always
